version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./configs/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
    network_mode: host
    

  mavlink-bridge:
    build:
      context: .
      dockerfile: DockerFileMavlinkMqtt
    container_name: mavlink_bridge
    depends_on:
      - mosquitto
    restart: unless-stopped
    network_mode: host

     
  service-web:
      build:
        context: .
        dockerfile: DockerFileWebApp
      volumes:
        - ./web_app/src:/app/src
        - ./web_app/public:/app/public
      network_mode: host
      environment:
        - CHOKIDAR_USEPOLLING=true
        - HOST=127.0.0.1
      stdin_open: true
      tty: true
      
